- platform: mqtt
  name: Front Door
  icon: mdi:door-open
  command_topic: "home/doors/output/frontdoor/set_on_ms"
  payload_on: "5000"
  optimistic: true
  state_topic: home/doors/output/frontdoor
  state_on: "ON"
  state_off: "OFF"
  qos: 1
  retain: false
  availability_topic: "home/doors/status"
  payload_available: "running"
  payload_not_available: "dead"

- platform: mqtt
  name: Garage Door
  icon: mdi:garage-open
  command_topic: "home/doors/output/garagedoor/set_on_ms"
  payload_on: "5000"
  optimistic: true
  state_topic: home/doors/output/garagedoor
  state_on: "ON"
  state_off: "OFF"
  qos: 1
  retain: false
  availability_topic: "home/doors/status"
  payload_available: "running"
  payload_not_available: "dead"