# Platform Configurations
homeassistant:
  name: "Home"
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Australia/Brisbane
  customize: !include_dir_merge_named customize

# Enable These Components
config:
conversation:
discovery:
frontend:
history:
logbook:
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
mqtt:
recorder:
sun:
updater:
ios: !include ./ios/ios.yaml
telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id
wemo:
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config

# Includes These Configurations
automation: !include_dir_merge_list automations
camera: !include_dir_merge_list cameras
device_tracker: !include_dir_merge_list device_trackers
group: !include_dir_merge_named groups
http: !include ./http/http.yaml
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_players
notify: !include_dir_merge_list notifiers
remote: !include_dir_merge_list remotes
scene: !include_dir_merge_list scenes
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
tts: !include_dir_merge_list tts
zone: !include_dir_merge_list zones
weblink: !include_dir_merge_named weblinks