# Platform Configurations
homeassistant:
  name: "Home"
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Australia/Brisbane
  customize: !include customize.yaml

# Enable These Components
config:
conversation:
discovery:
frontend:
history:
logbook:
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: warn
recorder:
sun:
updater:
#influxdb:
ios:
wemo:
emulated_hue:
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config

# Includes These Configurations
automation: !include_dir_merge_list automations
camera: !include_dir_merge_list cameras
device_tracker: !include_dir_merge_list device_trackers
group: !include groups.yaml
http: !include ./http/http.yaml
#input_boolean: !include inputboolean.yaml
#input_select: !include inputselect.yaml 
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_players
#mqtt: !include mqtt.yaml
notify: !include_dir_merge_list notifiers
remote: !include_dir_merge_list remotes
scene: !include_dir_merge_list scenes
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
tts: !include_dir_merge_list tts
zone: !include zones.yaml
weblink: !include weblinks.yaml
