# Platform Configurations
homeassistant:
  name: "Home"
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Australia/Brisbane
  customize: !include_dir_merge_named customize

# Enable These Components
alexa:
config:
cloud:
conversation:
discovery:
frontend:
# hassio:
history:
# homekit:
#   pincode: !secret homekit_pincode
logbook:
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: warn
  logs:
    homeassistant.components.recorder: debug
    homeassistant.components.logger: debug
    homeassistant.components.logbook: debug

mqtt:
  broker: 192.168.1.217
  username: mqtt
  password: mqtt
  port: 1884
  client_id: HASS
recorder:
sun:
updater:
ios: !include ./ios/ios.yaml
weather:
  - platform: bom
    name: BOM weather
    station: IDQ60801.94575
wemo:
zwave:
  usb_path: /dev/ttyACM0

# Includes These Configurations
alarm_control_panel: !include_dir_merge_list alarms
automation: !include_dir_merge_list automations
camera: !include_dir_merge_list cameras
device_tracker: !include_dir_merge_list device_trackers
group: !include_dir_merge_named groups
http: !include ./http/http.yaml
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_players
notify: !include_dir_merge_list notifiers
remote: !include_dir_merge_list remotes
scene: !include_dir_merge_list scenes
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
tts: !include_dir_merge_list tts
zone: !include_dir_merge_list zones
weblink: !include_dir_merge_named weblinks
