# Plex server
- platform: plex
  entity_namespace: plex

# Sonos
- platform: sonos
  interface_addr: 192.168.1.10
  entity_namespace: sonos

# Chromecast
- platform: cast
  entity_namespace: cast
  
# Onkyo Receiver Removed 9-Apr-2017 Not working [GH]
#- platform: onkyo
#  host: 192.168.1.199