- platform: template
  switches:
    tv:
      value_template: "{% if is_state('remote.media_room', 'on') %}on{% else %}off{% endif %}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.media_room
      turn_off:
        service: remote.turn_off
        entity_id: remote.media_room

