title: Home
views:

- title: Overview
  path: overview
  cards:
    - type: picture-glance
      title: Lounge Room
      camera_image: camera.loungeroom
      entities:
        binary_sensor.lounge_room_motion
        media_player.lounge
        media_player.lounge_cast
        light.lounge_room

    - type: picture-glance
      title: Media Room
      camera_image: camera.mediaroom
      entities:
        binary_sensor.media_room_motion
        remote.harmony_hub
        sensor.mediaroom_activity
        light.media_room_left
        light.media_room_right

    - type: picture-glance
      title: Front Yard
      camera_image: camera.frontdoor
      entitites:
        binary_sensor.front_door_motion
        switch.front_door

    - type: picture-glance
      title: Garage
      camera_image: camera.garage
      entities:
        binary_sensor.garage_motion
        media_player.garage
        switch.garage_door
        light.garage

    - type: picture-glance
      title: Backyard
      camera_image: camera.backyard
      entities:
        binary_sensor.back_yard_motion
        media_player.terrace
        media_player.terrace_chromcast

- title: Tim
  path: tim
  cards:
    - type: glance
      title: Tim Bedroom
      entities:
        fan.tim_bedroom
        sensor.tim_bedroom_temperature
        sensor.tim_bedroom_humidity
        sensor.tim_bedroom_aqi
        sensor.tim_bedroom_dust
        media_player.tim_speaker
        light.tim_bedroom_left
        light.tim_bedroom_right
    - type: history-graph
      title: Temperature
      entities:
        sensor.tim_bedroom_temperature

- title: Jess
  path: jess
  cards:
    - type: glance
      title: Jess Bedroom
      entities:
        fan.jess_bedroom
        sensor.jess_bedroom_temperature
        sensor.jess_bedroom_humidity
        sensor.jess_bedroom_aqi
        sensor.jess_bedroom_dust
        light.jess

- title: Parents
  path: parents
  cards:
    - type: glance
      title: Parents Bedroom
      entities:
        media_player.parents_bedroom
        light.parents_bedhead
        ight.parents_bedroom_2

- title: Alarm
  path: alarm
  cards:
    - type: alarm-panel
      title: Alarm
      eneity: alarm_control_panel.ha_alarm

- title: Weather
  path: weather
  cards:
    - type: weather-forecast
      title: Weather Forecast
      entity: weather.weather

- title: Media Room
  path: mediaroom
  cards:
    - type: horizontal-stack
      cards:
        - type: picture-entity
          entity: script.1547214476595
          image: "/local/Foxtel_Entertainment_Fox8.png"
          show_name: false
          show_state: false
