title: Home Assistant

name: Gazzzmo
views:
- icon: mdi:home
  title: Home
  id: home
  cards:
    - type: glance
      title: Lights
      show_state: false
      entities:
        - entity: light.lifx_garage
          tap_action: toggle
        - entity: light.lifx_jess
          tap_action: toggle
        - entity: light.lifx_lounge_room
          tap_action: toggle
        - entity: light.media_room
          tap_action: toggle
        - entity: light.lifx_media_room_a
          tap_action: toggle
        - entity: light.lifx_media_room_b
          tap_action: toggle
        - entity: light.lifx_parents_bedroom
          tap_action: toggle
        - entity: light.lifx_tim
          tap_action: toggle
        - entity: light.lifx_office
          tap_action: toggle

    - type: picture-glance
      title: Media Room
      entities: 
        - binary_sensor.blue_iris_mediaroom
        - remote.media_room
        - sensor.harmonyhub_mediaroom
        - script.watch_foxtel
        - script.play_xbox
        - script.watch_chromecast
        - script.watch_dvd
      camera_image: camera.mediaroom_camera

    - type: weather-forecast
      entity: weather.bom_brisbane

- icon: mdi:lightbulb
  title: Lights
  id: lights
  cards:
    - type: glance
      title: Lights
      show_state: false
      entities:
        - entity: light.lifx_garage
          tap_action: toggle
        - entity: light.lifx_jess
          tap_action: toggle
        - entity: light.lifx_lounge_room
          tap_action: toggle
        - entity: light.media_room
          tap_action: toggle
        - entity: light.lifx_media_room_a
          tap_action: toggle
        - entity: light.lifx_media_room_b
          tap_action: toggle
        - entity: light.lifx_office
          tap_action: toggle
        - entity: light.lifx_parents_bedroom
          tap_action: toggle
        - entity: light.lifx_tim
          tap_action: toggle


- icon: mdi:cctv
  title: CCTV
  id: cctv
  cards:
    - type: picture-entity
      entity: camera.backyard_camera
      name: Backyard

    - type: picture-entity
      entity: camera.garage_camera
      name: Garage

    - type: picture-entity
      entity: camera.lounge_camera
      name: Lounge Room

    - type: picture-entity
      entity: camera.mediaroom_camera
      name: Media Room

    - type: picture-entity
      entity: camera.office_camera
      name: Front Door
