title: Home Assistant

name: Gazzzmo
views:
- icon: mdi:home
  title: Home
  id: home
  cards:
    - type: glance
      title: Lights
      entities:
        - group.all_lights
    - type: picture-glance
      title: Media Room
      entities: 
        - binary_sensor.blue_iris_mediaroom
        - remote.media_room
        - sensor.harmonyhub_mediaroom
        - script.watch_foxtel
        - script.play_xbox
        - script.watch_chromecast
        - script.watch_dvd
      camera_image: camera.mediaroom_camera
    - type: weather-forecast
      entity: weather.bom_brisbane