resources:
  - url: /local/bignumber-card.js?v=3
    type: js
  - url: /local/monster-card.js?v=3
    type: js
  - url: /local/gauge-card.js?v=1
    type: js

name: Gazzzmo
views:
- icon: mdi:home
  title: Home
  id: home
  cards:
    - type: picture-glance
      title: Media Room
      image:
      camera_image: camera.mediaroom_camera
      entities:
        - camera.mediaroom_camera
        - binary_sensor.blue_iris_mediaroom
        - light.lifx_media_room_a
        - light.lifx_media_room_b
    - type: picture-glance
      title: Lounge Room
      image:
      navigation_path: /lovelace/lounge_room
      camera_image: 
      entities:
        - camera.lounge_camera
        - binary_sensor.blue_iris_lounge
        - light.lifx_lounge_room
        - media_player.lounge_tv