title: Home

resources:
  - url: /local/gauge-card.js?v=1
    type: js
  - url: /local/button-card.js
    type: module
    # Button Card from https://github.com/kuuji/button-card

#custom_updater:
#  card_urls: 
#    - https://raw.githubusercontent.com/kuuji/button-card/0.0.2/tracker.json

name: Gazzzmo
views:
- title: Dashboard
  icon: mdi:view-dashboard-variant
  id: dashboard
  cards:

    - type: "custom:button-card"
      entity: switch.front_door
      icon: mdi:door
      color_type: icon
      color: rgb(0,128,0)
      action: toggle
      name: Unlock Front Door
      style:
        - font-size: 12px
        - font-weight: bold

    - type: "custom:button-card"
      entity: switch.garage_door
      icon: mdi:garage
      color_type: icon
      color: rgb(255,0,0)
      action: toggle
      name: Garage Door
      style:
        - font-size: 12px
        - font-weight: bold

    - type: "custom:button-card"
      entity: light.lifx_garage
      icon: mdi:lamp
      color_type: icon
      color: auto
      action: toggle
      name: Garage
      style:
        - font-size: 12px
        - font-weight: bold

    - type: "custom:button-card"
      entity: light.lifx_lounge_room
      color: auto
      color_type: icon
      icon: mdi:lamp
      action: toggle
      name: Lounge Room
      style:
        - font-size: 12px
        - font-weight: bold

    - type: "custom:button-card"
      entity: light.lifx_parents_bedroom
      color_type: icon
      color: auto
      icon: mdi:lamp
      action: toggle
      name: Parents Bedroom
      style:
        - font-size: 12px
        - font-weight: bold

    - type: "custom:button-card"
      entity: light.lifx_jess
      icon: mdi:lamp
      color_type: icon
      color: auto
      action: toggle
      name: Jess
      style:
        - font-size: 12px
        - font-weight: bold

    - type: "custom:button-card"
      entity: group.family
      icon: mdi:compass
      color_type: icon
      color: auto
      name: Family
      style:
        - font-size: 12px
        - font-weight: bold

- title: Doors
  icon: mdi:door
  id: doors
  cards:
    - type: glance
      title: Doors
      entities:
        - entity: switch.front_door
          icon: mdi:door
          tap_action: toggle
        - entity: switch.garage_door
          icon: mdi:garage
          tap_action: toggle

- title: Media Room
  icon: mdi:television
  id: mediaroom
  cards:
    - type: picture-glance
      title: Media Room
      entities: 
        - binary_sensor.blue_iris_mediaroom
        - remote.media_room
        - sensor.harmonyhub_mediaroom
        - entity: script.watch_foxtel
          icon: mdi:facebook
        - entity: script.play_xbox
          icon: mdi:xbox
        - entity: script.watch_chromecast
          icon: mdi:cast
        - entity: script.watch_dvd
          icon: mdi:disc
      camera_image: camera.mediaroom_camera

- title: Weather
  icon: mdi:weather-cloudy
  id: weather
  cards:
    - type: weather-forecast
      entity: weather.bom_brisbane
    - type: custom:gauge-card
      title: Temperature
      entity: sensor.aeotec_zw100_multisensor_6_temperature
      min: 0
      max: 40
    - type: custom:gauge-card
      title: Humidity
      entity: sensor.aeotec_zw100_multisensor_6_relative_humidity
      min: 0
      max: 40
    - type: history-graph
      entities:
        - entity: sensor.aeotec_zw100_multisensor_6_temperature
          name: Temperature

- title: Lights
  icon: mdi:lightbulb
  id: lights
  cards:
    - type: glance
      title: Lights
      show_state: false
      entities:
        - entity: light.lifx_garage
          tap_action: toggle
        - entity: light.lifx_jess
          tap_action: toggle
        - entity: light.lifx_lounge_room
          tap_action: toggle
        - entity: light.media_room
          tap_action: toggle
        - entity: light.lifx_media_room_a
          tap_action: toggle
        - entity: light.lifx_media_room_b
          tap_action: toggle
        - entity: light.lifx_office
          tap_action: toggle
        - entity: light.lifx_parents_bedroom
          tap_action: toggle
        - entity: light.lifx_tim
          tap_action: toggle


- title: CCTV
  icon: mdi:cctv
  id: cctv
  cards:
    - type: picture-entity
      entity: camera.backyard_camera
      name: Backyard

    - type: picture-entity
      entity: camera.garage_camera
      name: Garage

    - type: picture-entity
      entity: camera.lounge_camera
      name: Lounge Room

    - type: picture-entity
      entity: camera.mediaroom_camera
      name: Media Room

    - type: picture-entity
      entity: camera.office_camera
      name: Front Door

- title: Map
  icon: mdi:map
  id: map
  cards:
    - type: map
      entities:
        - device_tracker.garethiphone
        - device_tracker.mandyiphone
        - device_tracker.timiphone
        - device_tracker.jessicasiphone
