- platform: bom
  zone_id: IDQ60801
  wmo_id: 94575
  monitored_conditions:
    - name
    - cloud
    - air_temp
    - press
    - rain_trace
    - rel_hum
    - vis_km
    - wind_dir
    - wind_spd_kmh