- platform: darksky
  api_key: !secret darksky_api_key
  update_interval: "00:15"
  monitored_conditions:
    - summary
    - daily_summary
    - hourly_summary
    - temperature_min
    - temperature_max
    - apparent_temperature
    - humidity
    - icon
    - precip_type
    - precip_probability
    - pressure
    - wind_bearing
    - wind_speed
