- platform: darksky
  entity_namespace: darksky
  api_key: !secret darksky_api_key
  name: "Forecast"
  update_interval: "00:15"
  monitored_conditions:
    - summary
    - daily_summary
    - hourly_summary
    - temperature_min
    - temperature_max