- platform: trend
  sensors:
    temp_falling:
      entity_id: sensor.bom_air_temp_c
      sample_duration: 7200
      min_gradient: -0.0008
      device_class: cold

    temp_rising:
      entity_id: sensor.bom_air_temp_c
      sample_duration: 7200
      min_gradient: 0.0008
      device_class: heat