- alias: "Gareth Bedside Flic"
  trigger:
    platform: state
    entity_id: binary_sensor.flic_80e4da729bfd
    from: "on"
    to: "off"
  action:
    service: light.toggle
    data:
      entity_id: light.lifx_parents_bedroom