alias: 'Update Available Notifications'
trigger:
  platform: state
  entity_id: updater.updater
action:
  - service: notify.telstrasms
    data:
      message: 'Update for Home Assistant is available.'
  - service: notify.notify
    data:
      message: 'Update for Home Assistant is available.'