- alias: "Notify Lounge Motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.blue_iris_lounge
      from: "off"
      to: "on"
  condition:
    condition: state
    entity_id: group.phones
    state: "not_home"
  action:
    service: notify.notify
    data_template:
      message: "Motion detected in the Living Room!"
      data:
        attachment:
          url: !secret lounge_image_url
          content-type: gif
        push:
          sound: "US-EN-Morgan-Freeman-Motion-In-Living-Room.wav"