- alias: "Tim Bedside Flic"
  trigger:
    platform: state
    entity_id: binary_sensor.flic_80e4da728fb6
    from: "on"
    to: "off"
  action:
    service: light.toggle
    data:
      entity_id: light.lifx_tim