- platform: mjpeg 
  name: "Lounge Camera"
  mjpeg_url: !secret lounge_camera_url
  still_image_url: !secret lounge_image_url
  username:  !secret blueiris_username
  password:  !secret blueiris_password
  authentication: basic