- platform: mjpeg 
  name: "Mediaroom Camera"
  mjpeg_url: !secret mediaroom_camera_url
  still_image_url: !secret mediaroom_image_url
  username:  !secret blueiris_username
  password:  !secret blueiris_password
  authentication: basic  